# https://github.com/tradichel/SecurityMetricsAutomation
# KMS/stacks/Key/cfn/Key.yaml
# author: @teriradichel @2ndsightlab
##############################################################
Parameters:
  EncryptArnParam:
    Type: String
  DecryptArnParam:
    Type: String
  KeyAliasParam:
    Type: String
  RotateParam:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
  DescParam:
    Type: String
  TimestampParam:
    Type: String
    Description: Force an update since AWS overwrites roles and CF doesn't recognize the change
    

Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      Description: !Ref DescParam
      EnableKeyRotation: !Ref RotateParam
      KeyPolicy:
        Version: 2012-10-17
        Id: key-default-1
        Statement:
          - Sid: "Allow Administration of the key and force update"
            Effect: Allow
            Principal:
              AWS:
                - !ImportValue KMSAdminsRoleArnExport
            Action:
              - kms:Create*
              - kms:Describe*
              - kms:Enable*
              - kms:List*
              - kms:Put*
              - kms:Update*
              - kms:Revoke*
              - kms:Disable*
              - kms:Get*
              - kms:Delete*
              - kms:ScheduleKeyDeletion
              - kms:CancelKeyDeletion
            Resource: "*"
          - Sid: Describe Key Only
            Effect: Allow
            Principal:
              AWS:
                - !Ref EncryptArnParam
                - !Ref DecryptArnParam
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:DescribeKey
            Resource: "*"
          - Sid: Get key policy
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - kms:GetKeyPolicy
            Resource: "*"
          - Sid: "Encrypt which apparently requires decrypt permissions"
            Effect: Allow
            Principal:
              AWS:
                - !Ref EncryptArnParam
            Action:
              - 'kms:Encrypt'
              - 'kms:ReEncrypt*'
              - 'kms:GenerateDataKey'
              - 'kms:GenerateDataKeyWithoutPlaintext'
              - 'kms:Decrypt'
            Resource: '*'
            Condition:
              "StringEquals":
                "kms:ViaService":
                    - !Sub "secretsmanager.${AWS::Region}.amazonaws.com"
          - Sid: Decrypt
            Effect: Allow
            Principal:
              AWS:
              - !Ref DecryptArnParam
            Action:
              - 'kms:Decrypt'
            Condition:
              "StringEquals":
                "kms:ViaService":
                    - !Sub "secretsmanager.${AWS::Region}.amazonaws.com"
            Resource: "*"

Outputs:
  KeyIDOutput:
    Value: !GetAtt KMSKey.KeyId
    Export:
      Name: !Sub ${KeyAliasParam}KeyIDExport
  KeyArnOutput:
    Value: !GetAtt KMSKey.Arn
    Export:
     Name: !Sub ${KeyAliasParam}KeyArnExport
  ForceUpdate:
    Value: !Sub "${TimestampParam}"

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################
