# https://github.com/tradichel/SecurityMetricsAutomation
# S3/stacks/cfn/Bucket.yaml
# author: @teriradichel @2ndsightlab
# The convolute nature of this template is due to what I 
# presume to be a bug. If anyone has a better way to do this,
# please submit a solution as a GitHub issue.
# https://medium.com/bugs-that-bite/cloudformation-bug-s3-server-access-logs-939dfb337e4d
################################################################
Parameters:
  ProfileParam:
    Type: String
    AllowedValues:
      - "orgroot"
      - "security"
      - "dev"
      - "qa"
      - "prod"
  BucketNameSuffixParam:
    Type: String
  KMSKeyIdParam:
    Type: String
  VersioningParam:
    Type: String
    AllowedValues: 
      - "Enabled"
      - "Suspended"
    Default: "Enabled"

Conditions:
  IsDev:
    !Equals
    - "dev"
    - !Ref ProfileParam
  
  IsAccessLogBucket:
    !Equals
    - !Ref BucketNameSuffixParam
    - "s3accesslogs"

  DoNotSetAccessLogBucket:
    !Or
      - Condition: IsDev
      - Condition: IsAccessLogBucket

  SetAccessLogBucket: 
    !Not [ Condition: DoNotSetAccessLogBucket ]

Resources:
    BucketAccessLogs:
      Type: AWS::S3::Bucket
      Condition: DoNotSetAccessLogBucket
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: 'aws:kms'
                KMSMasterKeyID: !Ref KMSKeyIdParam
        
        #Note: I would not use an account id in a public bucket
        #public buckets will be disallowed in this code-base
        BucketName: !Sub '${ProfileParam}-${AWS::AccountId}-${BucketNameSuffixParam}'
  
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

        VersioningConfiguration:
          Status: !Ref VersioningParam

    Bucket:
      Type: AWS::S3::Bucket
      Condition: SetAccessLogBucket
      Properties:
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            - ServerSideEncryptionByDefault:
                SSEAlgorithm: 'aws:kms'
                KMSMasterKeyID: !Ref KMSKeyIdParam

        #Note: I would not use an account id in a public bucket
        #public buckets will be disallowed in this code-base
        BucketName: !Sub '${ProfileParam}-${AWS::AccountId}-${BucketNameSuffixParam}'
        
        LoggingConfiguration: 
          DestinationBucketName: !Sub '${ProfileParam}-${AWS::AccountId}-s3accesslogs'
          LogFilePrefix: !Sub '${ProfileParam}-${AWS::AccountId}-${BucketNameSuffixParam}'

        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

        VersioningConfiguration:
          Status: !Ref VersioningParam

Outputs:
    BucketName:
      Value: !Sub '${ProfileParam}-${AWS::AccountId}-${BucketNameSuffixParam}'
      Export:
        Name: !Sub 'BucketName-${ProfileParam}-${BucketNameSuffixParam}'
    BucketDomainName:
      Condition: SetAccessLogBucket
      Value: !GetAtt [Bucket, DomainName]
      Export:
        Name: !Sub 'DomainName-${ProfileParam}-${BucketNameSuffixParam}'
    BucketUrl:
      Condition: SetAccessLogBucket
      Value: !GetAtt [Bucket, WebsiteURL]
      Export:
        Name: !Sub 'BucketUrl-${ProfileParam}-${BucketNameSuffixParam}'
    BucketArn:
      Condition: SetAccessLogBucket
      Value: !GetAtt [Bucket, Arn]
      Export: 
        Name: !Sub 'BucketArn-${ProfileParam}-${BucketNameSuffixParam}'
    BucketAccessLogsArn:
      Condition: DoNotSetAccessLogBucket
      Value: !GetAtt [BucketAccessLogs, Arn]
      Export:
        Name: !Sub 'BucketArn-${ProfileParam}-${BucketNameSuffixParam}'


