#jobs/DeployBatchJobCredentials/cfn/access_key_batch_job_admin.yaml
#@author: teriradichel @2ndsightlab
Resources:

  BatchJobAdminAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
        Status: Active
        UserName: !ImportValue batchjobadminuser

  BatchJobCredsSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
        Name: BatchJobAdminCredentials
        Description: BatchJobAdmin access key id and secret key
        KmsKeyId: !ImportValue batchcredentialkeyid
        SecretString:
            !Sub
                - "{accesskeyid:${id},secretkey:${secretkey}}"
                - id: !Ref BatchJobAdminAccessKey
                  secretkey: !GetAtt BatchJobAdminAccessKey.SecretAccessKey

#################################################################################
# Copyright Notice
# All Rights Reserved.
# All materials (the “Materials”) in this repository are protected by copyright 
# under U.S. Copyright laws and are the property of 2nd Sight Lab. They are provided 
# pursuant to a royalty free, perpetual license the person to whom they were presented 
# by 2nd Sight Lab and are solely for the training and education by 2nd Sight Lab.
#
# The Materials may not be copied, reproduced, distributed, offered for sale, published, 
# displayed, performed, modified, used to create derivative works, transmitted to 
# others, or used or exploited in any way, including, in whole or in part, as training 
# materials by or for any third party.
#
# The above copyright notice and this permission notice shall be included in all 
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT 
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION 
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE 
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################ 
