



Parameters:
  DomainNameParam:
    Type: String
  HostedZoneIdParam:
    Type: String
    Default: ""


Conditions:
  HostedZoneNotSet:
      - !Equals 
        - Ref HostedZoneId
        - ""

Resources: 
  MyCertificate: 
    Type: "AWS::CertificateManager::Certificate"
    Properties: 
      DomainName: !Ref DomainNameParam
      ValidationMethod: DNS
      DomainValidationOptions:
        !If
          - HostedZoneNotSet
          - !Ref AWS::NoValue
          -
            - DomainName: !Ref DomainNameParam
              HostedZoneId: !Ref HostedZoneIdParam

