# Create Root OU is not a process needing to be ran on every push. For that reasons it's defined as a manual workflow dispatch. 
# 
name: "CreateOrg"

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
    CreateOrg:
        runs-on: ubuntu-latest
        environment:
            name: proteus_org
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: install-aws-cli-action # Only needed to be installed for Act to use
          if: ${{ github.event.act }} 
          uses: unfor19/install-aws-cli-action@v1
        - name: Add profile credentials to ~/.aws/credentials
          env:
            AWS_DEFAULT_REGION: eu-west-2
          run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile OrgRoot --region eu-west-2
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile OrgRoot --region eu-west-2
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile GovernanceRoot --region eu-west-2
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile GovernanceRoot --region eu-west-2
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile Governance --region eu-west-2
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile Governance --region eu-west-2
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile Engineering --region eu-west-2
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile Engineering --region eu-west-2
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile CriticalResources --region eu-west-2
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile CriticalResources --region eu-west-2
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile Security --region eu-west-2
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile Security --region eu-west-2
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile Backup --region eu-west-2
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile Backup --region eu-west-2

        - name: Check credentials and profile
          env:
            AWS_DEFAULT_REGION: eu-west-2
          run: |
            aws sts get-caller-identity --profile OrgRoot --region eu-west-2
            aws sts get-caller-identity --profile GovernanceRoot --region eu-west-2
            chmod u+x ${GITHUB_WORKSPACE}/**/*.sh
        - name: Deploy AWS Organization and Root OU's # Used to skip this step when running locally with Act
          if: ${{ !github.event.act }} 
          env:
            AWS_DEFAULT_REGION: eu-west-2
          run: | 
            bash ${GITHUB_WORKSPACE}/Org/stacks/deploy.sh
        - name: Deploy Accounts to Governance OU's # Used to skip this step when running locally with Act
          if: ${{ !github.event.act }} 
          env:
            AWS_DEFAULT_REGION: eu-west-2
          run: | 
            bash ${GITHUB_WORKSPACE}/Org/stacks/Account/deploy_governance_accounts.sh
            
            
    
          

